# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bradar.proto\"?\n\x08Position\x12\x11\n\tlongitude\x18\x01 \x01(\x05\x12\x10\n\x08latitude\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\x05\x12\t\n\x01g\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\"N\n\x02\x44p\x12\x1b\n\x08position\x18\x01 \x01(\x0b\x32\t.Position\x12\x14\n\x0creflectivity\x18\x02 \x01(\x05\x12\x15\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x06.Color\"\x19\n\x04\x44\x61ta\x12\x11\n\x04\x44\x61ta\x18\x01 \x03(\x0b\x32\x03.Dpb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'radar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _POSITION._serialized_start = 15
    _POSITION._serialized_end = 78
    _COLOR._serialized_start = 80
    _COLOR._serialized_end = 120
    _DP._serialized_start = 122
    _DP._serialized_end = 200
    _DATA._serialized_start = 202
    _DATA._serialized_end = 227
# @@protoc_insertion_point(module_scope)


class Position(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _POSITION


class Color(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _COLOR


class Dp(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DP


class Data(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _DATA
